-- Схема магазина: справочники и сущности

CREATE TABLE IF NOT EXISTS "brand" (
    "id" VARCHAR(30) NOT NULL UNIQUE,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "manufacturer_country" (
    "id" VARCHAR(30) NOT NULL UNIQUE,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "category" (
    "id" VARCHAR(30) NOT NULL UNIQUE,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "cities" (
    "id" VARCHAR(30) NOT NULL UNIQUE,
    PRIMARY KEY("id")
);

-- Таблицы сущностей
CREATE TABLE IF NOT EXISTS "clients" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "city" VARCHAR(30) NOT NULL, -- тип должен совпадать с cities.id
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "PVZ" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "city" VARCHAR(30) NOT NULL,
    "street" VARCHAR(30) NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "article" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "category" VARCHAR(30),
    "name" VARCHAR(255),
    "cost" DECIMAL(10,2),
    "brand" VARCHAR(30),
    "manufacturing_country" VARCHAR(30),
    "specs" TEXT,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "orders" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "clientID" INTEGER NOT NULL,
    "PVZID" INTEGER NOT NULL,
    "date" TIMESTAMP NOT NULL, -- ИЗМЕНЕНО: теперь со временем
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "order_items" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "orderID" INTEGER NOT NULL,
    "articleID" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL DEFAULT 1,
    "unit_price" DECIMAL(10,2) NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "review" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "clientID" INTEGER NOT NULL,
    "articleID" INTEGER NOT NULL,
    "rating" INTEGER NOT NULL,
    "review_text" TEXT,
    PRIMARY KEY("id")
);

-- Настройка связей (Foreign Keys)
ALTER TABLE "clients" ADD CONSTRAINT "fk_client_city" FOREIGN KEY("city") REFERENCES "cities"("id");
ALTER TABLE "PVZ" ADD CONSTRAINT "fk_pvz_city" FOREIGN KEY("city") REFERENCES "cities"("id");
ALTER TABLE "orders" ADD CONSTRAINT "fk_order_client" FOREIGN KEY("clientID") REFERENCES "clients"("id");
ALTER TABLE "orders" ADD CONSTRAINT "fk_order_pvz" FOREIGN KEY("PVZID") REFERENCES "PVZ"("id");
ALTER TABLE "order_items" ADD CONSTRAINT "fk_items_order" FOREIGN KEY("orderID") REFERENCES "orders"("id");
ALTER TABLE "order_items" ADD CONSTRAINT "fk_items_article" FOREIGN KEY("articleID") REFERENCES "article"("id");
ALTER TABLE "article" ADD CONSTRAINT "fk_article_brand" FOREIGN KEY("brand") REFERENCES "brand"("id");
ALTER TABLE "article" ADD CONSTRAINT "fk_article_country" FOREIGN KEY("manufacturing_country") REFERENCES "manufacturer_country"("id");
ALTER TABLE "article" ADD CONSTRAINT "fk_article_category" FOREIGN KEY("category") REFERENCES "category"("id");
ALTER TABLE "review" ADD CONSTRAINT "fk_review_client" FOREIGN KEY("clientID") REFERENCES "clients"("id");
ALTER TABLE "review" ADD CONSTRAINT "fk_review_article" FOREIGN KEY("articleID") REFERENCES "article"("id");
